---
# Required by the OpenFeature Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    dt.owner: "platform_team"
  name: open-feature-operator
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://open-feature.github.io/open-feature-operator'
      targetRevision: v0.5.1
      chart: open-feature-operator
      helm:
        values: |
          flagdProxyConfiguration:
            image:
              tag: v0.3.2
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2