apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: users
spec:
  forProvider:
    # If not set, metadata.name will be used instead.
    name: "All Users"
    parentIdRef:
      name: 0
    path: "users"
    description: "All users are in this group"
    #sharedWithGroups:
    #   - groupId: "example group id 1"
    #     groupAccessLevel: "example access level 1"
    #   - groupId: "example group id 2"
    #     groupAccessLevel: "example access level 2"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-users
    namespace: crossplane
---
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group
spec:
  forProvider:
    description: example group description
    name: Example Group
    parentIdRef:
      name: example-parent-group
    path: example-group-path
    sharedWithGroups:
      - groupAccessLevel: 50
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system