apiVersion: projects.gitlab.crossplane.io/v1beta1
kind: Project
metadata:
  name: app1-template
spec:
  forProvider:
    # If not set, metadata.name will be used instead.
    name: "Application 1 Template"
    #namespaceIdRef:
    #  name: example-group
    description: "template for app1"
    initializeWithReadme: true
    defaultBranch: main
    visibility: public
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-project-example-project
    namespace: crossplane