configs:
- id: myk8scluster
  config:
    name: hot-day-platform-engineering
    parameters:
      certCheckEnabled: "false"
      clusterActive: "true"
      eventsActive: "true"
      workloadIntegrationEnabled: "true"
    template: config.json
    skip: false
  type:
    api: kubernetes-credentials