---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "${{ values.projectName }}-${{ values.userName }}"
  namespace: "${{ values.projectName }}-${{ values.userName }}-${{ values.releaseStage }}-cd"
  labels:
    dt.owner: "${{ values.userName }}"
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 2s}
      - setWeight: 40
      - pause: {duration: 2s}
      - setWeight: 60
      - pause: {duration: 2s}
      - setWeight: 80
      - pause: {duration: 2s}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: userinterface
  template:
    metadata:
      labels:
        app.kubernetes.io/name: userinterface
        app.kubernetes.io/part-of: "${{ values.projectName }}-${{ values.userName }}"
        app.kubernetes.io/version: "${{ values.appVersion }}"
        dynatrace-release-stage: "${{ values.releaseStage }}"
    spec:
      containers:
      - name: rollouts-demo
        image: grabnerandi/simplenodeservice:${{ values.appVersion }}
        env:
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_PRODUCT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/part-of']
        - name: DT_RELEASE_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['dynatrace-release-stage']
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
