apiVersion: metrics.keptn.sh/v1alpha1
kind: KeptnMetricsProvider
metadata:
  name: dynatrace
spec:
  targetServer: "https://wls34801.live.dynatrace.com"
  secretKeyRef:
    name: dt-metrics-read-token
    key: DT_TOKEN