kind: KeptnMetricsProvider
metadata:
  name: dev-dynatrace
  namespace: keptn
spec:
  type: dynatrace
  targetServer: "https://wls34801.live.dynatrace.com"
  secretKeyRef:
    name: dt-metrics-read-token
    key: DT_TOKEN