---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dt-details
  namespace: opentelemetry
spec:
  encryptedData:
    DT_OTEL_TRACE_INGEST_TOKEN: AgCrVwcwK40ISNoqujEKl9nIHTDxJbxceoCmuNdhA0efCPg2VlRnGzAAFvCWNTCcxM3h0TQTHwBMRW3n3IhRQqphy5Zmg4Oo0yVVSRti1sQc6g3MPB2VbUntC/nTcbZwGf8tHPI2b4NomacLeD8BTrnOdsq4AFgrYdlgS2X/Z+hVhyOHs2SOilxhAt9O+3y1GG6+f04Hcme9dYWkwA1wZJnURfyUMI45G7MkQyoQurhTpNfWrbBfY9sKu2aevRaGRU9LGmczFTUTZNUywN3yIP77OGug2FgOod+4CsdcJERx2u1utjoKXomZdkgB4CgVl6r/4EIqFM1BDWHAxguKeqTbqBFfMKjZbOfHWvax9xdDOgljM7xIUNLsKszQNOdF7fPp+ZK+qDMU4SP9rp7o4hUl1qq6MXTa2E5DquhqneJWrh3ROtRAduc9ZCujbmLXfW81hMxqyJEoh86tFOwcoRCEcG4o+2Ps7asudjuB03El0unH+qJngYmEail1X1GVV9Lc/LDwTcKED3b49pkjBt7shN2FczsGZljlavN3VhqYvuxMK76q9Q89fLiY986xT0QBVT49WSr6Yt4j4g2u9+EnZQyl3LjRAWiWMIWmO9W4eCqTVSYmM7g3dqqrCP/vQQcoQuYCeUEPtY0x39e5Ix8YhV0e1AicHkYZWhle4T3GxWKYY0vTAki6B6LD7BwoyCcFU78ZtK4SPxfgl/3G//RI8D/AMeH1c2s5G0+opyksMFs1NF1KJpSsaTMWmJXskilVZ/vlNIGEwWnXp1mCFNbAbYMde9LgC0t8sa4Cmsm3oGQA7j6TlR+FxP/rg/yn6h0=
    DT_URL: AgAxyK1O1oegcz3C72kxKxULERHjASpfgUFUn8k5MTY6irwsEvtZG805LRN3KNJYfp6Lg2J5e4twLjb7El8MUaY4RBQtjNGJY3+AmEo6SOWVITRF/iEzJQbCquYdvMWdVYptIbd5RfAkiTbkpGVKASapC4p+8yMtvHJAmO6yYBaF+dvm58fwXfbh4LPM2DIRkbWUEaXWxJELUpbCHdB761wV8wOfzSl5PrQvas+vU9j0poHN5Br4foLytJ8+zvFHqzQzk3WQueGWEMwUuGSayX/NDLTfkhO7owhi9rqtvH4O4oAja7NSxpiKRLRgvDSYE3+Hxplh09fZ60U/WAdbJTWUjOyG9wA2Ql32lLKVEJnULScgaKAg3ewwEjpeIc4kHyeTj/VmKqFquhVG+M9aYYbqJsasfxYKbqffe7HwM5wARnAwl2ke4OLWU35NhP4uECveahj0wVXORH9mvAkP7yW0/Sx0M7w/c/1ojlQ2WhBvrwa3+PVmsCAoaEPo8CtBdM1XvmQcnlqVU2epCB2iGnCHzcsRdf/IuIXdoumM6ZDH3CcfbNcR/ZOtny9kAlnTA0yQG94zpgYZnv9PWTo7Hl3dECKBTG/igmVLMvaz5DD2XN6FV/s4L7ng7OVKquNbX+5hGJq1Da7744tHF6mpxoVFelgpD3OtfAGFMk4rt9Xw6pHfOo2zgJE0yi53FzEcZWQ5D5dCiy6OluL9VJefnWh6mc4/MdNtQOz/j+/OgroYRrbUCg==
  template:
    metadata:
      creationTimestamp: null
      name: dt-details
      namespace: opentelemetry
