# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gitlab
#   namespace: gitlab
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "https"
#     service.beta.kubernetes.io/aws-load-balancer-internal: "false"
#     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
# spec:
#   rules:
#     #- host: gitlab.agardner.hotday.keptn.sh
#     - host: gitlab.dtu-test-s17-2afbea.dynatrace.training
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: gitlab-webservice-default
#                 port:
#                   number: 8080
