apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    dt.owner: "platform_team"
  name: gitlab
  namespace: argocd
spec:
  source:
    repoURL: 'https://charts.gitlab.io'
    targetRevision: 7.4.1
    chart: gitlab
    helm:
      values: |
        certmanager:
          install: false
        certmanager-issuer:
            email: "dthotday@example.com"
        upgradeCheck:
          enabled: false
        global:
          edition: "ce"
          # the "tracing" section is just a guess
          # I do not think it works
          # Apparently gitlab only supports OpenTracing
          # https://docs.gitlab.com/charts/charts/globals.html#tracing
          tracing:
            connection:
              string: "http://otel-collector.opentelemetry.svc.cluster.local:4318"
              urlTemplate: "https://gitlab.gitlab.agardner.hotday.keptn.sh/{{ service }}/{{ correlation_id  }}"
          hosts:
            domain: gitlab.agrabner-hotday.keptn.sh
            nginx-ingress:
              enabled: false
          ingress:
            class: nginx
            configureCertmanager: false
            # enabled: false
            tls:
              enabled: false
        nginx-ingress:
          enabled: false
  destination:
    namespace: gitlab
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
