apiVersion: v1
kind: Service
metadata:
  annotations:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/port: '9236'
  labels:
    app: gitaly
    app.kubernetes.io/instance: gitlab
    chart: gitaly-7.5.2
    heritage: Helm
    release: gitlab
  name: gitlab-gitaly
  namespace: gitlab
spec:
  ports:
  - name: tcp-gitaly
    port: 8075
    protocol: TCP
    targetPort: grpc-gitaly
  - name: http-metrics
    port: 9236
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: gitaly
    release: gitlab
  type: ClusterIP